"""fix containers tables

Revision ID: 390e8eed5c76
Revises: 438462aa1232
Create Date: 2024-08-23 22:48:52.992201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390e8eed5c76'
down_revision: Union[str, None] = '438462aa1232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adp_containers', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('adp_containers', 'description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
    op.alter_column('adp_containers', 'date_assigned',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('adp_containers', 'date_public',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cna_containers', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('cna_containers', 'date_assigned',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cna_containers', 'date_public',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cna_containers', 'date_public',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cna_containers', 'date_assigned',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cna_containers', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('adp_containers', 'date_public',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('adp_containers', 'date_assigned',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('adp_containers', 'description',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)
    op.alter_column('adp_containers', 'title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
