"""remove contraint with regex

Revision ID: fe1fa4d1ee17
Revises: 390e8eed5c76
Create Date: 2024-08-23 23:06:56.594260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1fa4d1ee17'
down_revision: Union[str, None] = '390e8eed5c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
