"""create tables

Revision ID: 007de9846928
Revises: 
Create Date: 2024-08-23 23:56:22.933122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007de9846928'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cves',
    sa.Column('id', sa.String(length=29), nullable=False),
    sa.Column('state', sa.Enum('PUBLISHED', 'RESERVED', 'REJECTED', name='cvestate'), nullable=False),
    sa.Column('assigner_org_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='The UUID for the organization to which the CVE ID was originally assigned.'),
    sa.Column('assigner_short_name', sa.String(length=32), nullable=True),
    sa.Column('date_reserved', sa.Date(), nullable=True),
    sa.Column('date_published', sa.Date(), nullable=True),
    sa.Column('date_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adp_containers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('date_assigned', sa.Date(), nullable=True),
    sa.Column('date_public', sa.Date(), nullable=True),
    sa.Column('cve_record_id', sa.String(length=29), nullable=False),
    sa.ForeignKeyConstraint(['cve_record_id'], ['cves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cna_containers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('date_assigned', sa.Date(), nullable=True),
    sa.Column('date_public', sa.Date(), nullable=True),
    sa.Column('cve_record_id', sa.String(length=29), nullable=False),
    sa.ForeignKeyConstraint(['cve_record_id'], ['cves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cna_containers')
    op.drop_table('adp_containers')
    op.drop_table('cves')
    # ### end Alembic commands ###
