"""add ondelete cascade

Revision ID: 9cfb7394116c
Revises: 007de9846928
Create Date: 2024-08-27 01:01:50.913966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfb7394116c'
down_revision: Union[str, None] = '007de9846928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('adp_containers_cve_record_id_fkey', 'adp_containers', type_='foreignkey')
    op.create_foreign_key(None, 'adp_containers', 'cves', ['cve_record_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cna_containers_cve_record_id_fkey', 'cna_containers', type_='foreignkey')
    op.create_foreign_key(None, 'cna_containers', 'cves', ['cve_record_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cna_containers', type_='foreignkey')
    op.create_foreign_key('cna_containers_cve_record_id_fkey', 'cna_containers', 'cves', ['cve_record_id'], ['id'])
    op.drop_constraint(None, 'adp_containers', type_='foreignkey')
    op.create_foreign_key('adp_containers_cve_record_id_fkey', 'adp_containers', 'cves', ['cve_record_id'], ['id'])
    # ### end Alembic commands ###
